Feat: Add json support
media-cloud-ai/mcai_worker_sdk pull request #162
Opened 2021-04-12 16:36 UTC by nipierre

2021-04-13 10:10 UTC, nipierre commented on rs_mcai_worker_sdk/src/message/media/json/decoder.rs
> +      if value.is_object() {
Invert condition

2021-04-13 10:15 UTC, nipierre commented on rs_mcai_worker_sdk/src/message/media/mod.rs
> +    StreamDescriptor {
Modify stream descriptor with 2 entries :
 - index
 - configuration, which is an enum running on the different configuration possible (image, audio, EBU, JSON)

2021-04-14 09:19 UTC, valnoel commented on rs_mcai_worker_sdk/src/message/media/mod.rs
> +  Data(),
Are the empty brackets necessary?

2021-04-14 09:19 UTC, valnoel commented on rs_mcai_worker_sdk/src/message/media/mod.rs
> +  Image(Option<ImageConfiguration>),
Are the `Option`s really useful?

2021-04-14 09:19 UTC, valnoel commented on rs_mcai_worker_sdk/src/message/media/source.rs
> +  Json(Option<JsonDecoder>),
Are the `Option`s really useful?

2021-04-14 09:19 UTC, valnoel commented on rs_mcai_worker_sdk/src/message/media/source.rs
> +  Data(),
Are the empty brackets necessary?

2021-04-15 08:00 UTC, valnoel requested changes

2021-04-15 08:00 UTC, valnoel commented on rs_mcai_worker_sdk/src/message/media/json/decoder.rs
> +  pub fn decode_content(&mut self, json_content: &str) -> Result<Option<Json>, String> {
Could you add unit tests? On this function at least...

2021-04-15 10:13 UTC, nipierre commented on rs_mcai_worker_sdk/src/message/media/json/decoder.rs
> +  pub fn decode_content(&mut self, json_content: &str) -> Result<Option<Json>, String> {
Done for the decoding function, for the rest we probably should implement a whole Packet generator.. :/

2021-04-15 12:08 UTC, valnoel approved these changes

2021-04-15 16:02 UTC, merged